/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Robert' at '15.10.17 16:17' with Gradle 2.13
 *
 * @author Robert, @date 15.10.17 16:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
